import re

with open(r'C:\Users\ankur\Documents\projects\med\travel-health-finder\apps\web\src\app\profile\page.tsx', 'r', encoding='utf-8') as f:
    content = f.read()

# The error was caused by the regex style replacer producing output like:
# style={{ 'fontVariationSettings': ''FILL' 1' }}
# We need to find patterns like `''...` inside style={{ ... }} and convert them.

# Let's just blindly fix the known bad strings generated by our previous script
content = content.replace("''FILL' 1'", "\"'FILL' 1\"")
content = content.replace("''FILL' 0, 'wght' 400, 'GRAD' 0, 'opsz' 24'", "\"'FILL' 0, 'wght' 400, 'GRAD' 0, 'opsz' 24\"")

with open(r'C:\Users\ankur\Documents\projects\med\travel-health-finder\apps\web\src\app\profile\page.tsx', 'w', encoding='utf-8') as f:
    f.write(content)

print("Fixed syntax errors in style objects")
