"""Add doctors table

Revision ID: 96b355ae0eb6
Revises: 0001
Create Date: 2026-06-24 20:22:53.304084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b355ae0eb6'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('dp_score', sa.String(length=50), nullable=True),
    sa.Column('npv_value', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('consult_fee', sa.String(length=50), nullable=True),
    sa.Column('years_of_experience', sa.String(length=50), nullable=True),
    sa.Column('speciality', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_city'), 'doctors', ['city'], unique=False)
    op.create_index(op.f('ix_doctors_name'), 'doctors', ['name'], unique=False)
    op.create_index(op.f('ix_doctors_speciality'), 'doctors', ['speciality'], unique=False)
    op.add_column('feedback', sa.Column('doctor_id', sa.UUID(as_uuid=False), nullable=False))
    op.drop_index('ix_feedback_google_place_id', table_name='feedback')
    op.create_index(op.f('ix_feedback_doctor_id'), 'feedback', ['doctor_id'], unique=False)
    op.create_foreign_key(None, 'feedback', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('feedback', 'google_place_id')
    op.add_column('saved_places', sa.Column('doctor_id', sa.UUID(as_uuid=False), nullable=False))
    op.drop_index('ix_saved_places_google_place_id', table_name='saved_places')
    op.drop_constraint('uq_user_place', 'saved_places', type_='unique')
    op.create_index(op.f('ix_saved_places_doctor_id'), 'saved_places', ['doctor_id'], unique=False)
    op.create_unique_constraint('uq_user_doctor', 'saved_places', ['user_id', 'doctor_id'])
    op.create_foreign_key(None, 'saved_places', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('saved_places', 'google_place_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_places', sa.Column('google_place_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'saved_places', type_='foreignkey')
    op.drop_constraint('uq_user_doctor', 'saved_places', type_='unique')
    op.drop_index(op.f('ix_saved_places_doctor_id'), table_name='saved_places')
    op.create_unique_constraint('uq_user_place', 'saved_places', ['user_id', 'google_place_id'])
    op.create_index('ix_saved_places_google_place_id', 'saved_places', ['google_place_id'], unique=False)
    op.drop_column('saved_places', 'doctor_id')
    op.add_column('feedback', sa.Column('google_place_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_index(op.f('ix_feedback_doctor_id'), table_name='feedback')
    op.create_index('ix_feedback_google_place_id', 'feedback', ['google_place_id'], unique=False)
    op.drop_column('feedback', 'doctor_id')
    op.drop_index(op.f('ix_doctors_speciality'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_name'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_city'), table_name='doctors')
    op.drop_table('doctors')
    # ### end Alembic commands ###
